Force git_build configuration.
This option is required to generate all needed headers for Qt and QtWebkit.

diff --git a/src/qt/qtbase/configure b/src/qt/qtbase/configure
--- a/src/qt/qtbase/configure
+++ b/src/qt/qtbase/configure
@@ -3596,16 +3596,14 @@ fi
 # -----------------------------------------------------------------------------
 
 # symlink includes
-if [ -e "$relpath/.git" ]; then
-    if [ -z "$PERL" ]; then
-        echo
-        echo "You need perl in your PATH to make a build from GIT."
-        echo "Cannot proceed."
-        exit 1
-    fi
-
-    "$relpath/bin/syncqt.pl" -minimal -module QtCore "$relpath" || exit 1
+if [ -z "$PERL" ]; then
+    echo
+    echo "You need perl in your PATH to make a build"
+    echo "Cannot proceed."
+    exit 1
 fi
+
+"$relpath/bin/syncqt.pl" -minimal -module QtCore "$relpath" || exit 1
 
 # $1: input variable name (awk regexp)
 # $2: optional output variable name
@@ -3732,11 +3730,7 @@ if true; then ###[ '!' -f "$outpath/bin/qmake" ];
 
         echo "BUILD_PATH = $adjoutpath" >> "$mkfile"
         echo "SOURCE_PATH = $adjrelpath" >> "$mkfile"
-        if [ -e "$relpath/.git" ]; then
-            echo 'INC_PATH = $(BUILD_PATH)/include' >> "$mkfile"
-        else
-            echo 'INC_PATH = $(SOURCE_PATH)/include' >> "$mkfile"
-        fi
+        echo 'INC_PATH = $(SOURCE_PATH)/include' >> "$mkfile"
         echo "QMAKESPEC = $adjqmakespec" >> "$mkfile"
         echo "QT_VERSION = $QT_VERSION" >> "$mkfile"
         echo "EXTRA_CFLAGS = $EXTRA_CFLAGS" >> "$mkfile"
